const KEY="familyhub_v1";
const defaults={emergency:[{name:"Ambulance",emoji:"🚑",phone:"108"},{name:"Police",emoji:"🚓",phone:"112"},{name:"Fire",emoji:"🚒",phone:"101"},{name:"Hospital",emoji:"🏥",phone:""}],members:[],contacts:[],medicines:[],documents:[],reminders:[],notes:[],customFields:[]};
let data=load();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaults)}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function tel(p){return p?`<a href="tel:${esc(p)}">${esc(p)}</a>`:"<span class='small'>Not added</span>"}
function render(){
document.getElementById("emergencyGrid").innerHTML=data.emergency.map(x=>`<div class="emergency-card"><div class="emoji">${esc(x.emoji)}</div><strong>${esc(x.name)}</strong>${tel(x.phone)}</div>`).join("");
document.getElementById("memberList").innerHTML=data.members.length?data.members.map((m,i)=>`<div class="member"><div class="avatar">${esc(m.emoji||"👤")}</div><div class="member-main"><strong>${esc(m.name)}</strong><small>${esc(m.relation||"Family member")} ${m.phone?"• "+esc(m.phone):""}</small></div><div class="member-actions"><button class="mini" onclick="viewMember(${i})">👁️</button><button class="mini" onclick="editMember(${i})">✏️</button></div></div>`).join(""):`<div class="empty">No family members yet.<br>Tap + Add to create one.</div>`;
}
function modal(title,body){document.getElementById("modalTitle").textContent=title;document.getElementById("modalBody").innerHTML=body;document.getElementById("modal").classList.add("open")}
function close(){document.getElementById("modal").classList.remove("open")}
document.getElementById("closeModal").onclick=close;document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")close()};
function memberForm(i=null){
let m=i===null?{name:"",relation:"",phone:"",emoji:"👤",blood:"",allergies:"",doctor:"",notes:""}:data.members[i];
modal(i===null?"Add Family Member":"Edit Family Member",`<form class="form" id="mf"><label>Name<input required name="name" value="${esc(m.name)}"></label><label>Relation<input name="relation" value="${esc(m.relation)}"></label><label>Phone<input type="tel" name="phone" value="${esc(m.phone)}"></label><label>Emoji<input name="emoji" value="${esc(m.emoji)}"></label><label>Blood group<input name="blood" value="${esc(m.blood)}"></label><label>Allergies<input name="allergies" value="${esc(m.allergies)}"></label><label>Family doctor<input name="doctor" value="${esc(m.doctor)}"></label><label>Notes<textarea name="notes">${esc(m.notes)}</textarea></label>${data.customFields.map((f,j)=>`<label>${esc(f.name)}<input name="custom_${j}" value="${esc(m["custom_"+j]||"")}"></label>`).join("")}<button class="primary-btn">Save</button>${i!==null?`<button type="button" class="danger-btn" onclick="deleteMember(${i})">Delete Member</button>`:""}</form>`);
document.getElementById("mf").onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));i===null?data.members.push(o):data.members[i]=o;save();close()}
}
window.editMember=i=>memberForm(i);window.deleteMember=i=>{if(confirm("Delete this member?")){data.members.splice(i,1);save();close()}};window.viewMember=i=>{let m=data.members[i];modal(m.name,`<div class="card"><p>Relation: ${esc(m.relation||"Not added")}</p><p>📞 ${tel(m.phone)}</p><p>🩸 Blood: ${esc(m.blood||"Not added")}</p><p>⚠️ Allergies: ${esc(m.allergies||"None")}</p><p>👨‍⚕️ Doctor: ${esc(m.doctor||"Not added")}</p><p>📝 ${esc(m.notes||"No notes")}</p></div><button class="primary-btn" onclick="editMember(${i})">Edit</button>`)};
document.getElementById("addMemberBtn").onclick=()=>memberForm();
document.getElementById("editEmergency").onclick=()=>{modal("Emergency Numbers",data.emergency.map((x,i)=>`<div class="list-row"><label>${esc(x.name)}<input data-e="${i}" value="${esc(x.phone)}"></label></div>`).join("")+`<button class="primary-btn" id="se">Save</button>`);document.getElementById("se").onclick=()=>{data.emergency.forEach((x,i)=>x.phone=document.querySelector(`[data-e="${i}"]`).value);save();close()}};
function collection(type,title,a,b){let rows=data[type].map((x,i)=>`<div class="list-row"><div class="row-head"><strong>${esc(x[a])}</strong><button class="mini" onclick="del('${type}',${i},'${title}','${a}','${b}')">🗑️</button></div><div class="small">${esc(x[b]||"")}</div><p>${esc(x.notes||"")}</p></div>`).join("");modal(title,(rows||'<div class="empty">Nothing added yet.</div>')+`<button class="primary-btn" id="add">+ Add</button>`);document.getElementById("add").onclick=()=>addItem(type,title,a,b)}
function addItem(type,title,a,b){modal("Add "+title.replace(/s$/,""),`<form class="form" id="cf"><label>${a}<input required name="${a}"></label><label>${b}<input name="${b}"></label><label>Notes<textarea name="notes"></textarea></label><button class="primary-btn">Save</button></form>`);document.getElementById("cf").onsubmit=e=>{e.preventDefault();data[type].push(Object.fromEntries(new FormData(e.target)));save();close();collection(type,title,a,b)}}
window.del=(t,i,title,a,b)=>{if(confirm("Delete this item?")){data[t].splice(i,1);save();collection(t,title,a,b)}};
function settings(){modal("⚙️ Customize FamilyHub",`<div class="card"><h3>Custom Family Fields</h3><p class="small">These fields appear in every family member profile.</p><div id="fl">${data.customFields.map((f,i)=>`<div class="list-row"><strong>${esc(f.name)}</strong> <button class="mini" onclick="df(${i})">🗑️</button></div>`).join("")||'<div class="empty">No custom fields.</div>'}</div><button class="primary-btn" id="af">+ Add Field</button></div><div class="card"><h3>Backup</h3><button class="secondary" onclick="exportData()">Export Backup</button></div>`);document.getElementById("af").onclick=()=>{let n=prompt("Field name");if(n?.trim()){data.customFields.push({name:n.trim()});save();settings()}}}
window.df=i=>{if(confirm("Delete this field?")){data.customFields.splice(i,1);save();settings()}};
function exportData(){let b=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="familyhub-backup.json";a.click()}
document.getElementById("settingsBtn").onclick=settings;document.getElementById("exportBtn").onclick=exportData;
document.getElementById("importInput").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.members||!x.emergency)throw 0;data=x;save();alert("Backup restored.")}catch{alert("Invalid FamilyHub backup.")}};r.readAsText(f)};
document.querySelectorAll(".tile").forEach(x=>x.onclick=()=>openSection(x.dataset.section));document.querySelectorAll(".nav-item").forEach(x=>x.onclick=()=>x.dataset.nav==="home"?close():x.dataset.nav==="settings"?settings():openSection(x.dataset.nav));
function openSection(s){if(s==="medical")modal("🏥 Medical","<div class='empty'>Medical details are currently managed inside each family member profile.</div>");else if(s==="contacts")collection("contacts","Contacts","name","phone");else if(s==="medicines")collection("medicines","Medicines","name","details");else if(s==="documents")collection("documents","Documents","name","details");else if(s==="reminders")collection("reminders","Reminders","name","details");else if(s==="notes")collection("notes","Notes","title","body")}
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});render();